/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Daniel
 */
public class CreateClass extends javax.swing.JDialog {

    private ImageIcon imagen;
    private Icon icono;
    
    /**
     * Creates new form CreateWarrior
     */
    public CreateClass(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.pintarImagen(this.background, "src\\main\\java\\Images\\fondoEstrellado.jpg");
        this.pintarImagen(this.lblActImg, "src\\main\\java\\Images\\PennyWise.jpg");
        this.pintarImagen(this.lblSelWarrior, "src\\main\\java\\Images\\PennyWise.jpg");
        this.pintarImagen(this.lblSelWeapon1, "src\\main\\java\\Images\\PennyWise.jpg");
        this.pintarImagen(this.lblSelWeapon2, "src\\main\\java\\Images\\PennyWise.jpg");
        this.pintarImagen(this.lblSelWeapon3, "src\\main\\java\\Images\\PennyWise.jpg");
        this.pintarImagen(this.lblSelWeapon4, "src\\main\\java\\Images\\PennyWise.jpg");
        this.pintarImagen(this.lblSelWeapon5, "src\\main\\java\\Images\\PennyWise.jpg");
        
        try{
                Image image = ImageIO.read(new File("src\\main\\java\\Images\\Left.png"));
                Image imagenBtn = image.getScaledInstance(btnLeft.getWidth(), btnLeft.getHeight(), image.SCALE_DEFAULT);
                btnLeft.setIcon(new ImageIcon(imagenBtn));
                
                image = ImageIO.read(new File("src\\main\\java\\Images\\Right.png"));
                imagenBtn = image.getScaledInstance(btnRight.getWidth(), btnRight.getHeight(), image.SCALE_DEFAULT);
                btnRight.setIcon(new ImageIcon(imagenBtn));
            }
            catch (Exception e){

            }
    }
    
    private void pintarImagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(
                                    lbl.getWidth(), 
                                    lbl.getHeight(), 
                                    Image.SCALE_DEFAULT));
        lbl.setIcon(this.icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLeft = new javax.swing.JButton();
        btnRight = new javax.swing.JButton();
        lblChoosenClass = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblActImg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblSelWarrior = new javax.swing.JLabel();
        lblSelWeapon1 = new javax.swing.JLabel();
        lblSelWeapon2 = new javax.swing.JLabel();
        lblSelWeapon3 = new javax.swing.JLabel();
        lblSelWeapon4 = new javax.swing.JLabel();
        lblSelWeapon5 = new javax.swing.JLabel();
        lblAttackedByText3 = new javax.swing.JLabel();
        ignore = new javax.swing.JLabel();
        ignore1 = new javax.swing.JLabel();
        btnContinue = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select your Class");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLeft.setBorderPainted(false);
        btnLeft.setContentAreaFilled(false);
        getContentPane().add(btnLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 60, 50));

        btnRight.setBorderPainted(false);
        btnRight.setContentAreaFilled(false);
        getContentPane().add(btnRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 60, 50));

        lblChoosenClass.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblChoosenClass.setForeground(new java.awt.Color(255, 255, 255));
        lblChoosenClass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChoosenClass.setText("Choosen Class:");
        getContentPane().add(lblChoosenClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 260, -1));

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Choose Your Warrior:");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));
        getContentPane().add(lblActImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 420, 310));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setForeground(new java.awt.Color(51, 255, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Warrior:", null},
                {"Weapon 1:", null},
                {"Weapon 2:", null},
                {"Weapon 3:", null},
                {"Weapon 4:", null},
                {"Weapon 1:", null}
            },
            new String [] {
                "", ""
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 260, 110));
        getContentPane().add(lblSelWarrior, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 80, 80));
        getContentPane().add(lblSelWeapon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 80, 80));
        getContentPane().add(lblSelWeapon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 80, 80));
        getContentPane().add(lblSelWeapon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 80, 80));
        getContentPane().add(lblSelWeapon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 80, 80));
        getContentPane().add(lblSelWeapon5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 80, 80));

        lblAttackedByText3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAttackedByText3.setForeground(new java.awt.Color(255, 255, 255));
        lblAttackedByText3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAttackedByText3.setText("NameWarrior");
        getContentPane().add(lblAttackedByText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 420, -1));

        ignore.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ignore.setForeground(new java.awt.Color(255, 255, 255));
        ignore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ignore, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, 30, 20));

        ignore1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ignore1.setForeground(new java.awt.Color(255, 255, 255));
        ignore1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ignore1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 420, 20));

        btnContinue.setText("Continue");
        getContentPane().add(btnContinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 80, 40));

        btnSelect.setText("Select");
        getContentPane().add(btnSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 480, 80, 40));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateClass dialog = new CreateClass(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnLeft;
    private javax.swing.JButton btnRight;
    private javax.swing.JButton btnSelect;
    private javax.swing.JLabel ignore;
    private javax.swing.JLabel ignore1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblActImg;
    private javax.swing.JLabel lblAttackedByText3;
    private javax.swing.JLabel lblChoosenClass;
    private javax.swing.JLabel lblSelWarrior;
    private javax.swing.JLabel lblSelWeapon1;
    private javax.swing.JLabel lblSelWeapon2;
    private javax.swing.JLabel lblSelWeapon3;
    private javax.swing.JLabel lblSelWeapon4;
    private javax.swing.JLabel lblSelWeapon5;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
