/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import SocketClient.Client;
import java.awt.Image;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel
 */
public class CreateClass extends javax.swing.JDialog {

    private ImageIcon imagen;
    private Icon icono;
    private int counterChars = 0;
    private int warriorCount = 1;
    private static Client client;
    private String setCharacteristicsCommand = "setCharacteristics";
    
    /**
     * Creates new form CreateWarrior
     */
    public CreateClass(javax.swing.JDialog parent, boolean modal, Client client) {
        super(parent, modal);
        initComponents();
        
        this.client = client;
        
        //WINDOW IN MIDDLE OF THE SCREEN
        this.setLocationRelativeTo(this);
        
        this.pintarImagen(this.background, "src\\main\\java\\Images\\fondoEstrellado.jpg");
        this.pintarImagen(this.lblActImg, "src\\main\\java\\Images\\PennyWise.jpg");
        this.pintarImagen(this.lblSelWarrior, "src\\main\\java\\Images\\PennyWise.jpg");
        this.pintarImagen(this.lblSelWeapon1, "src\\main\\java\\Images\\PennyWise.jpg");
        this.pintarImagen(this.lblSelWeapon2, "src\\main\\java\\Images\\PennyWise.jpg");
        this.pintarImagen(this.lblSelWeapon3, "src\\main\\java\\Images\\PennyWise.jpg");
        this.pintarImagen(this.lblSelWeapon4, "src\\main\\java\\Images\\PennyWise.jpg");
        this.pintarImagen(this.lblSelWeapon5, "src\\main\\java\\Images\\PennyWise.jpg");
        
        try{
                Image image = ImageIO.read(new File("src\\main\\java\\Images\\Left.png"));
                Image imagenBtn = image.getScaledInstance(btnLeft.getWidth(), btnLeft.getHeight(), image.SCALE_DEFAULT);
                btnLeft.setIcon(new ImageIcon(imagenBtn));
                
                image = ImageIO.read(new File("src\\main\\java\\Images\\Right.png"));
                imagenBtn = image.getScaledInstance(btnRight.getWidth(), btnRight.getHeight(), image.SCALE_DEFAULT);
                btnRight.setIcon(new ImageIcon(imagenBtn));
            }
        catch (Exception e){

        }
        
        
    }
    
    private void pintarImagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(
                                    lbl.getWidth(), 
                                    lbl.getHeight(), 
                                    Image.SCALE_DEFAULT));
        lbl.setIcon(this.icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLeft = new javax.swing.JButton();
        btnRight = new javax.swing.JButton();
        lblChoosenClass = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblActImg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tCharacteristics = new javax.swing.JTable();
        lblSelWarrior = new javax.swing.JLabel();
        lblSelWeapon1 = new javax.swing.JLabel();
        lblSelWeapon2 = new javax.swing.JLabel();
        lblSelWeapon3 = new javax.swing.JLabel();
        lblSelWeapon4 = new javax.swing.JLabel();
        lblSelWeapon5 = new javax.swing.JLabel();
        lblActSelection = new javax.swing.JLabel();
        ignore = new javax.swing.JLabel();
        ignore1 = new javax.swing.JLabel();
        btnContinue = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select your Class");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLeft.setBorderPainted(false);
        btnLeft.setContentAreaFilled(false);
        getContentPane().add(btnLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 60, 50));

        btnRight.setBorderPainted(false);
        btnRight.setContentAreaFilled(false);
        btnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightActionPerformed(evt);
            }
        });
        getContentPane().add(btnRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 60, 50));

        lblChoosenClass.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblChoosenClass.setForeground(new java.awt.Color(255, 255, 255));
        lblChoosenClass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChoosenClass.setText("Choosen Class 1:");
        getContentPane().add(lblChoosenClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 260, -1));

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Choose Your Warrior:");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));
        getContentPane().add(lblActImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 420, 330));

        tCharacteristics.setBackground(new java.awt.Color(0, 0, 0));
        tCharacteristics.setForeground(new java.awt.Color(51, 255, 0));
        tCharacteristics.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Warrior:", null},
                {"Element:", null},
                {"Weapon 1:", null},
                {"Weapon 2:", null},
                {"Weapon 3:", null},
                {"Weapon 4:", null},
                {"Weapon5:", null}
            },
            new String [] {
                "", ""
            }
        ));
        jScrollPane1.setViewportView(tCharacteristics);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 260, 130));
        getContentPane().add(lblSelWarrior, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 80, 80));
        getContentPane().add(lblSelWeapon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 80, 80));
        getContentPane().add(lblSelWeapon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 80, 80));
        getContentPane().add(lblSelWeapon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 80, 80));
        getContentPane().add(lblSelWeapon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 80, 80));
        getContentPane().add(lblSelWeapon5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, 80, 80));

        lblActSelection.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblActSelection.setForeground(new java.awt.Color(255, 255, 255));
        lblActSelection.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblActSelection.setText("NameWarrior");
        getContentPane().add(lblActSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 420, -1));

        ignore.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ignore.setForeground(new java.awt.Color(255, 255, 255));
        ignore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ignore, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, 30, 20));

        ignore1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ignore1.setForeground(new java.awt.Color(255, 255, 255));
        ignore1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ignore1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, 420, 20));

        btnContinue.setText("Continue");
        btnContinue.setEnabled(false);
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });
        getContentPane().add(btnContinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 80, 40));

        btnSelect.setText("Select");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 80, 40));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        //CODE TO ADD WARRIOR AND WEAPONS
        DefaultTableModel model = (DefaultTableModel)tCharacteristics.getModel();

        switch(counterChars){
            case 6 ->{
                
                btnSelect.setEnabled(false);
                btnContinue.setEnabled(true);        
                this.setCharacteristicsCommand += " " + lblActSelection.getText();
                tCharacteristics.setValueAt(lblActSelection.getText(), counterChars, 1);
                System.out.println(setCharacteristicsCommand);
            }
            default ->{
                this.setCharacteristicsCommand += " " + lblActSelection.getText();
                tCharacteristics.setValueAt(lblActSelection.getText(), counterChars, 1);
            }
        }
        
        counterChars++;
    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        
        switch(this.warriorCount){
            case 4 ->{
                try {
                    //SENDING INFO TO SERVER
                    client.sendMessage(setCharacteristicsCommand);
                    JOptionPane.showMessageDialog(null, "Class #" + warriorCount + " created succesfully");
                    dispose();
                } 
                catch (Exception ex) {
                    System.out.println("ERROR SENDING CHARACTERISTICS TO SERVER");
                }
            }            
            default -> { 
                JOptionPane.showMessageDialog(null, "Class #" + warriorCount + " created succesfully");
                DefaultTableModel model = (DefaultTableModel)tCharacteristics.getModel();
                for (int i = 0; i < 7; i++){
                    tCharacteristics.setValueAt("", i, 1);
                }
                warriorCount++;
                lblChoosenClass.setText("Choosen Class " + warriorCount + ":");
                counterChars = 0;
                
                btnSelect.setEnabled(true);
                btnContinue.setEnabled(false);   
                
            }
        }
    }//GEN-LAST:event_btnContinueActionPerformed

    private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateClass dialog = new CreateClass(new javax.swing.JDialog(), true, client);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnLeft;
    private javax.swing.JButton btnRight;
    private javax.swing.JButton btnSelect;
    private javax.swing.JLabel ignore;
    private javax.swing.JLabel ignore1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblActImg;
    private javax.swing.JLabel lblActSelection;
    private javax.swing.JLabel lblChoosenClass;
    private javax.swing.JLabel lblSelWarrior;
    private javax.swing.JLabel lblSelWeapon1;
    private javax.swing.JLabel lblSelWeapon2;
    private javax.swing.JLabel lblSelWeapon3;
    private javax.swing.JLabel lblSelWeapon4;
    private javax.swing.JLabel lblSelWeapon5;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tCharacteristics;
    // End of variables declaration//GEN-END:variables
}
