/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import java.awt.Color;

/**
 *
 * @author Daniel
 */
public class GameScreen extends javax.swing.JDialog {

    /**
     * Creates new form GameScreen
     */
    public GameScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //change background color
        getContentPane().setBackground(Color.DARK_GRAY);
        //taConsole.setBackground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tUserStats = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tAgainstStats = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        taConsole = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tRanking = new javax.swing.JTable();
        pTeam = new javax.swing.JPanel();
        lblTeam1 = new javax.swing.JLabel();
        lblTeam2 = new javax.swing.JLabel();
        lblTeam3 = new javax.swing.JLabel();
        lblTeam4 = new javax.swing.JLabel();
        lblLifeChar1 = new javax.swing.JLabel();
        lblYourTeam = new javax.swing.JLabel();
        lblLifeChar2 = new javax.swing.JLabel();
        lblLifeChar3 = new javax.swing.JLabel();
        lblLifeChar4 = new javax.swing.JLabel();
        lblNameChar2 = new javax.swing.JLabel();
        lblNameChar1 = new javax.swing.JLabel();
        lblNameChar3 = new javax.swing.JLabel();
        lblNameChar4 = new javax.swing.JLabel();
        lblActChar = new javax.swing.JLabel();
        lblLifeActChar = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tUserStats1 = new javax.swing.JTable();
        pAtacckedBy = new javax.swing.JLayeredPane();
        lblAttackedBy = new javax.swing.JLabel();
        pAtaccking = new javax.swing.JLayeredPane();
        lblAttacking = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Game Screen");
        setBackground(new java.awt.Color(0, 0, 0));

        tUserStats.setBackground(new java.awt.Color(0, 0, 0));
        tUserStats.setForeground(new java.awt.Color(51, 255, 0));
        tUserStats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Wins:", null},
                {"Losses:", ""},
                {"Attacks:", null},
                {"Success;", null},
                {"Failed:", null},
                {"Giveup:", null}
            },
            new String [] {
                "MY STATUS:", "#XX"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tUserStats);

        tAgainstStats.setBackground(new java.awt.Color(0, 0, 0));
        tAgainstStats.setForeground(new java.awt.Color(51, 255, 0));
        tAgainstStats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Wins:", null},
                {"Losses:", ""},
                {"Attacks:", null},
                {"Success;", null},
                {"Failed:", null},
                {"Giveup:", null}
            },
            new String [] {
                "AGAINST:", "#XX"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tAgainstStats);

        taConsole.setBackground(new java.awt.Color(0, 0, 0));
        taConsole.setColumns(20);
        taConsole.setForeground(new java.awt.Color(51, 255, 0));
        taConsole.setLineWrap(true);
        taConsole.setRows(5);
        taConsole.setSelectionColor(new java.awt.Color(255, 153, 0));
        jScrollPane4.setViewportView(taConsole);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tRanking.setBackground(new java.awt.Color(0, 0, 0));
        tRanking.setForeground(new java.awt.Color(51, 255, 0));
        tRanking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null},
                {"", "", null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "RANKING:", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tRanking);

        pTeam.setBackground(new java.awt.Color(0, 0, 0));

        lblLifeChar1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblLifeChar1.setForeground(new java.awt.Color(255, 255, 255));
        lblLifeChar1.setText("100%");

        lblYourTeam.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblYourTeam.setForeground(new java.awt.Color(255, 255, 255));
        lblYourTeam.setText("YOUR TEAM");

        lblLifeChar2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblLifeChar2.setForeground(new java.awt.Color(255, 255, 255));
        lblLifeChar2.setText("100%");

        lblLifeChar3.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblLifeChar3.setForeground(new java.awt.Color(255, 255, 255));
        lblLifeChar3.setText("100%");

        lblLifeChar4.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblLifeChar4.setForeground(new java.awt.Color(255, 255, 255));
        lblLifeChar4.setText("100%");

        lblNameChar2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblNameChar2.setForeground(new java.awt.Color(255, 255, 255));
        lblNameChar2.setText("MICHAEL MYERS");

        lblNameChar1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblNameChar1.setForeground(new java.awt.Color(255, 255, 255));
        lblNameChar1.setText("MICHAEL MYERS");

        lblNameChar3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblNameChar3.setForeground(new java.awt.Color(255, 255, 255));
        lblNameChar3.setText("MICHAEL MYERS");

        lblNameChar4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblNameChar4.setForeground(new java.awt.Color(255, 255, 255));
        lblNameChar4.setText("MICHAEL MYERS");

        lblActChar.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblActChar.setForeground(new java.awt.Color(255, 255, 255));
        lblActChar.setText("ACTUAL CHARACTER");

        lblLifeActChar.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblLifeActChar.setForeground(new java.awt.Color(255, 255, 255));
        lblLifeActChar.setText("100%");

        tUserStats1.setBackground(new java.awt.Color(0, 0, 0));
        tUserStats1.setForeground(new java.awt.Color(51, 255, 0));
        tUserStats1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Weapon1", null, null, null, null, null, null, null, null, null, null},
                {"Weapon2", null, null, null, null, null, null, null, null, null, null},
                {"Weapon3", null, null, null, null, null, null, null, null, null, null},
                {"Weapon4", null, null, null, null, null, null, null, null, null, null},
                {"Weapon1", null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Weapons", "", "", "", "", "", "", "", "", "", ""
            }
        ));
        jScrollPane5.setViewportView(tUserStats1);

        javax.swing.GroupLayout pTeamLayout = new javax.swing.GroupLayout(pTeam);
        pTeam.setLayout(pTeamLayout);
        pTeamLayout.setHorizontalGroup(
            pTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTeamLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblLifeChar1)
                .addGap(86, 86, 86)
                .addComponent(lblLifeChar2)
                .addGap(78, 78, 78)
                .addComponent(lblLifeChar3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLifeChar4)
                .addGap(44, 44, 44))
            .addGroup(pTeamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTeam3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameChar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pTeamLayout.createSequentialGroup()
                        .addComponent(lblTeam1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTeam2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTeam4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pTeamLayout.createSequentialGroup()
                        .addComponent(lblNameChar2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNameChar3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNameChar4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTeamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
            .addGroup(pTeamLayout.createSequentialGroup()
                .addGroup(pTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pTeamLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblYourTeam))
                    .addGroup(pTeamLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblActChar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLifeActChar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pTeamLayout.setVerticalGroup(
            pTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTeamLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblYourTeam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTeam3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTeam4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTeam2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTeam1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLifeChar1)
                    .addComponent(lblLifeChar2)
                    .addComponent(lblLifeChar3)
                    .addComponent(lblLifeChar4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameChar2)
                    .addComponent(lblNameChar1)
                    .addComponent(lblNameChar3)
                    .addComponent(lblNameChar4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActChar)
                    .addComponent(lblLifeActChar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pAtacckedBy.setBackground(new java.awt.Color(0, 0, 0));
        pAtacckedBy.setForeground(new java.awt.Color(0, 0, 0));

        pAtacckedBy.setLayer(lblAttackedBy, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pAtacckedByLayout = new javax.swing.GroupLayout(pAtacckedBy);
        pAtacckedBy.setLayout(pAtacckedByLayout);
        pAtacckedByLayout.setHorizontalGroup(
            pAtacckedByLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAttackedBy, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );
        pAtacckedByLayout.setVerticalGroup(
            pAtacckedByLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAttackedBy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pAtaccking.setBackground(new java.awt.Color(0, 0, 0));
        pAtaccking.setForeground(new java.awt.Color(0, 0, 0));

        pAtaccking.setLayer(lblAttacking, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pAtacckingLayout = new javax.swing.GroupLayout(pAtaccking);
        pAtaccking.setLayout(pAtacckingLayout);
        pAtacckingLayout.setHorizontalGroup(
            pAtacckingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAttacking, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );
        pAtacckingLayout.setVerticalGroup(
            pAtacckingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAttacking, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pAtacckedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pAtaccking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pTeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pAtacckedBy)
                        .addGap(3, 3, 3)
                        .addComponent(pAtaccking))
                    .addComponent(pTeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GameScreen dialog = new GameScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblActChar;
    private javax.swing.JLabel lblAttackedBy;
    private javax.swing.JLabel lblAttacking;
    private javax.swing.JLabel lblLifeActChar;
    private javax.swing.JLabel lblLifeChar1;
    private javax.swing.JLabel lblLifeChar2;
    private javax.swing.JLabel lblLifeChar3;
    private javax.swing.JLabel lblLifeChar4;
    private javax.swing.JLabel lblNameChar1;
    private javax.swing.JLabel lblNameChar2;
    private javax.swing.JLabel lblNameChar3;
    private javax.swing.JLabel lblNameChar4;
    private javax.swing.JLabel lblTeam1;
    private javax.swing.JLabel lblTeam2;
    private javax.swing.JLabel lblTeam3;
    private javax.swing.JLabel lblTeam4;
    private javax.swing.JLabel lblYourTeam;
    private javax.swing.JLayeredPane pAtacckedBy;
    private javax.swing.JLayeredPane pAtaccking;
    private javax.swing.JPanel pTeam;
    private javax.swing.JTable tAgainstStats;
    private javax.swing.JTable tRanking;
    private javax.swing.JTable tUserStats;
    private javax.swing.JTable tUserStats1;
    private javax.swing.JTextArea taConsole;
    // End of variables declaration//GEN-END:variables
}
